# ---
# name: Deploy to Github pages
# on:
#   push:
#     branches:
#       - main
#   # workflow_dispatch:
#   # pull_request:
#   #   branches:
#   #     - main
#   #   types:
#   #     - closed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure Git Credentials
#         run: |
#           git config user.name github-actions[bot]
#           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.x
#       - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
#       - uses: actions/cache@v4
#         with:
#           key: mkdocs-material-${{ env.cache_id }}
#           path: .cache
#           restore-keys: |
#             mkdocs-material-
#       - run: pip install mkdocs-material 
#       - run: mkdocs gh-deploy --force
#   # deploy:
#   #   name: Deploy MkDocs project to Github pages
#   #   if: github.event.pull_request.merged == true
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: Checkout repository
#   #       uses: actions/checkout@v4
#   #       with:
#   #         fetch-depth: 0
#   #     - name: Install Python
#   #       uses: actions/setup-python@v5
#   #       with:
#   #         python-version: 3.x
#   #     - run: pip3 install -r requirements.txt
#   #     - run: mkdocs gh-deploy --force